### PR TITLE
Got a lot of FP with Nextcloud 26

### PR DESCRIPTION
**Pull request by prghix**
So asking for comments :)

### CODE REVIEW

**Comment by RedXanadu** [comment]
Hi,

The same as with #21, please edit your opening comment to describe the change and its purpose, and please use an appropriate rule ID for your proposed new rule. Follow the rule ID pattern already established in the file. Thanks!

**Comment by azurit** [comment]
@prghix This is already fixed here:
https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/blob/25467b4f440295a9959d997868eda405a746b87a/plugins/nextcloud-rule-exclusions-before.conf#L129

**Comment by prghix** [comment]
> @prghix This is already fixed here:
> 
> https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/blob/25467b4f440295a9959d997868eda405a746b87a/plugins/nextcloud-rule-exclusions-before.conf#L129

I have my rules from April 7th... this commit was already included.

Looks like it wasnt enough, still got FPs.

I'll provide debug...

**Comment by azurit** [comment]
@prghix Any news? Thank you.

**Comment by theseion** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
