### PR TITLE
Temporary fix for /apps/text/session

### PR DESCRIPTION
**Pull request by prghix**

### CODE REVIEW

**Comment by RedXanadu** [comment]
Hi @prghix,

Please edit your opening comment so that it provides a description of what this change is doing and why you are proposing it.

Please also give your rule an `id`. You can follow the pattern of rule IDs already present in the file :slightly_smiling_face:

**Comment by azurit** [comment]
@prghix Will you look at this? Thank you!

**Comment by prghix** [comment]
> @prghix Will you look at this? Thank you!

of course, this is high on my priority list...

**Comment by azurit** [comment]
@prghix Any news? Thank you!

**Comment by prghix** [comment]
> @prghix Any news? Thank you!

Hello.. I watch all the discussions over here and also in coreruleset/coreruleset.

Will update the CRS and test against several NC instances first...

**Comment by theseion** [comment]
Closing due to inactivity.

**Pull request closed without merging**
