### PR TITLE
fix: use correct GH workflow setup

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by theseion** [comment]
Requires https://github.com/coreruleset/crs-plugin-test-action/pull/5.

**Comment by theseion** [comment]
Requires https://github.com/coreruleset/crs-plugin-test-action/pull/6.

**Comment by theseion** [comment]
@azurit I had to adjust the phase of your new rule to 1. Tracking this down was a bit complicated because multiple rules react to request methods and / or the URI containing fragments of `remote.php`, `dav`, `...files`, and `...uploads`.

**Review by fzipi — APPROVED** [review]
Awesome!

**Review by fzipi — APPROVED** [review]

**Pull request merged**
