### PR TITLE
chore: update version to 1.1.0

### PR DESCRIPTION
**Pull request by theseion**
@EsadCetiner just added support for Nextcloud Office. This warrants a new release, IMO.

### CODE REVIEW

**Comment by EsadCetiner** [comment]
I agree it's a major change, but iirc the markdown text editor has changed and that's a major feature in core. I can look into it in a few hours and open a PR if there's false positives.

**Comment by theseion** [comment]
That would be great. Better to have those fixed before the release.

**Comment by RedXanadu** [comment]
Merge conflicts have appeared :weary: 

The CHANGELOG file should reflect the 1.1.0 release and the reasons for it / updates included.

Otherwise, this seems fine in principle.

**Review by RedXanadu — COMMENTED** [review]
Merge conflicts have appeared :weary: 

The CHANGELOG file should reflect the 1.1.0 release and the reasons for it / updates included.

Otherwise, this seems fine in principle.

**Review by RedXanadu — COMMENTED** [review]
Failing ~50% of tests.

**Comment by theseion** [comment]
This is blocked by the other PR atm.

**Comment by theseion** [comment]
Now it's ready @RedXanadu.

**Review by RedXanadu — COMMENTED** [review]
Waiting until the outcome of tonight's meeting so we know what needs to go in the CHANGELOG file, or if that file should be removed entirely.

**Review by RedXanadu — APPROVED** [review]
CHANGELOG begone!

This looks good to me :slightly_smiling_face:

**Pull request merged**
